name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Show Files
        run: ls -R

      - name: Build
        run: |
          xcodebuild \
          -scheme VitaGo \
          -sdk iphonesimulator \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: VitaGo
          path: .
