name: Build VitaGo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Swift Package
        run: swift build

      - name: Create Artifact Folder
        run: |
          mkdir artifact
          cp -R .build artifact/build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VitaGo-Build
          path: artifact
